onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/array_idle_o
add wave -noupdate /tb/cfg_tile_i
add wave -noupdate /tb/cfg_write_addr_i
add wave -noupdate /tb/cfg_write_data_i
add wave -noupdate /tb/cfg_write_enable_i
add wave -noupdate /tb/clear_outputs_i
add wave -noupdate /tb/clk_i
add wave -noupdate /tb/CLK_PERIOD
add wave -noupdate /tb/context_addr_o
add wave -noupdate /tb/DMEM_ADDR_W
add wave -noupdate /tb/dut/clk_i
add wave -noupdate /tb/dut/rst_ni
add wave -noupdate /tb/dut/run_i
add wave -noupdate /tb/dut/set_context_i
add wave -noupdate /tb/dut/set_context_addr_i
add wave -noupdate /tb/dut/clear_outputs_i
add wave -noupdate /tb/dut/execute_enable_o
add wave -noupdate /tb/dut/context_addr_o
add wave -noupdate /tb/dut/stall_o
add wave -noupdate /tb/dut/array_idle_o
add wave -noupdate /tb/dut/cfg_write_enable_i
add wave -noupdate /tb/dut/cfg_tile_i
add wave -noupdate /tb/dut/cfg_write_addr_i
add wave -noupdate /tb/dut/cfg_write_data_i
add wave -noupdate /tb/dut/row_in_valid_i
add wave -noupdate /tb/dut/row_in_data_i
add wave -noupdate /tb/dut/row_in_ready_o
add wave -noupdate /tb/dut/row_out_valid_o
add wave -noupdate /tb/dut/row_out_data_o
add wave -noupdate /tb/dut/row_out_source_o
add wave -noupdate /tb/dut/row_out_ready_i
add wave -noupdate /tb/dut/dmem_host_valid_i
add wave -noupdate /tb/dut/dmem_host_write_i
add wave -noupdate /tb/dut/dmem_host_bank_i
add wave -noupdate /tb/dut/dmem_host_addr_i
add wave -noupdate /tb/dut/dmem_host_wdata_i
add wave -noupdate /tb/dut/dmem_host_ready_o
add wave -noupdate /tb/dut/dmem_host_rvalid_o
add wave -noupdate /tb/dut/dmem_host_rdata_o
add wave -noupdate /tb/dut/rowq_valid_q
add wave -noupdate /tb/dut/rowq_push
add wave -noupdate /tb/dut/rowq_pop
add wave -noupdate /tb/dut/memq_valid_q
add wave -noupdate /tb/dut/memq_push
add wave -noupdate /tb/dut/memq_pop
add wave -noupdate /tb/dut/row_route_consumed_q
add wave -noupdate /tb/dut/mem_route_consumed_q
add wave -noupdate /tb/dut/row_route_need
add wave -noupdate /tb/dut/mem_route_need
add wave -noupdate /tb/dut/rowq_can_accept
add wave -noupdate /tb/dut/memq_can_accept
add wave -noupdate /tb/dut/store_pending_q
add wave -noupdate /tb/dut/endpoint_stall
add wave -noupdate /tb/dut/dmem_engine_idle
add wave -noupdate /tb/dut/dmem_host_fire
add wave -noupdate /tb/dut/noc_row
add wave -noupdate /tb/dut/noc_col
add wave -noupdate /tb/dut/noc_src
add wave -noupdate /tb/dut/noc_dst
add wave -noupdate /tb/dut/noc_tile_id
add wave -noupdate /tb/dut/endpoint_index
add wave -noupdate /tb/dut/queue_index
add wave -noupdate /tb/dut/ptr_row
add wave -noupdate /tb/dut/ptr_col
add wave -noupdate /tb/dut/mem_col
add wave -noupdate /tb/dut/mem_reset_tile
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
